In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.simplefilter(action= 'ignore')

In [5]:
satislar = pd.read_csv('satislar.csv')
df = satislar.copy()
df.head()

Aylar  Satislar
0      8   19671.5
1     10   23102.5
2     11   18865.5
3     13   21762.5
4     14   19945.5

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Aylar     30 non-null     int64  
 1   Satislar  30 non-null     float64
dtypes: float64(1), int64(1)
memory usage: 608.0 bytes


In [7]:
df.isnull().sum()

Aylar       0
Satislar    0
dtype: int64

## Basit Linear Regression (Simple Linear Regression)

In [79]:
# Bagimli ve Bagimsiz Degisken Atamasi

X = df[['Aylar']]
y = df[['Satislar']]

In [80]:
# Train Test 

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=0)

In [81]:
'''# Verilerin Standartizasyonu 

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)
y_train = sc.fit_transform(y_train)
y_test = sc.fit_transform(y_test)
'''
X_test

Aylar
2      11
28     64
13     26
10     25
26     59
24     54
27     59
11     25
17     34
22     49

In [82]:
X_train

Aylar
5      19
16     32
8      20
14     29
23     50
20     42
1      10
29     65
6      19
4      14
18     37
19     37
9      24
7      20
25     55
3      13
0       8
21     44
15     31
12     25

In [83]:
# Linear Regression objesi olusturma

from sklearn.linear_model import LinearRegression
lr = LinearRegression()

# Fit etmek
lr.fit(X_train, y_train)

# Tahmin 
tahmin = lr.predict(X_test)
tahmin

array([[20126.21865404],
       [57740.29412655],
       [30771.7117123 ],
       [30062.01217508],
       [54191.79644047],
       [50643.29875438],
       [54191.79644047],
       [30062.01217508],
       [36449.30801003],
       [47094.80106829]])

In [84]:
print(tahmin - y_test)

       Satislar
2   1260.718654
28 -3455.205873
13  2231.211712
10 -1546.987825
26 -4292.703560
24 -4072.201246
27 -2125.703560
11  2165.012175
17 -5094.691990
22 -3556.198932


In [111]:
#print(y_test)
print(f'{np.array(tahmin):.2f}')

TypeError: unsupported format string passed to numpy.ndarray.__format__

In [112]:
np.array(tahmin)

array([[20126.21865404],
       [57740.29412655],
       [30771.7117123 ],
       [30062.01217508],
       [54191.79644047],
       [50643.29875438],
       [54191.79644047],
       [30062.01217508],
       [36449.30801003],
       [47094.80106829]])

In [113]:
tahmin

array([[20126.21865404],
       [57740.29412655],
       [30771.7117123 ],
       [30062.01217508],
       [54191.79644047],
       [50643.29875438],
       [54191.79644047],
       [30062.01217508],
       [36449.30801003],
       [47094.80106829]])