In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.simplefilter(action= 'ignore')

In [2]:
adv = pd.read_csv('Advertising.csv', usecols=[1,2,3,4])
df = adv.copy()
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [15]:
# Kutuphane import edilir
from sklearn.linear_model import LinearRegression 
from sklearn.model_selection import train_test_split, cross_val_score, cross_val_predict
from sklearn.metrics import mean_squared_error , r2_score

#X = df.drop('sales', axis=1)

In [12]:
X
y = df['sales']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.20, random_state=42)

lm = LinearRegression()
model = lm.fit(X_train, y_train)


array([0.04472952, 0.18919505, 0.00276111])

In [13]:
model.coef_

array([0.04472952, 0.18919505, 0.00276111])

In [14]:
model.intercept_

2.979067338122629

In [18]:
model.mean_squared_error(y_test, model.predict(X_test))

AttributeError: 'LinearRegression' object has no attribute 'mean_squared_error'

In [20]:
model.predict(X_test)

array([16.4080242 , 20.88988209, 21.55384318, 10.60850256, 22.11237326,
       13.10559172, 21.05719192,  7.46101034, 13.60634581, 15.15506967,
        9.04831992,  6.65328312, 14.34554487,  8.90349333,  9.68959028,
       12.16494386,  8.73628397, 16.26507258, 10.27759582, 18.83109103,
       19.56036653, 13.25103464, 12.33620695, 21.30695132,  7.82740305,
        5.80957448, 20.75753231, 11.98138077,  9.18349576,  8.5066991 ,
       12.46646769, 10.00337695, 21.3876709 , 12.24966368, 18.26661538,
       20.13766267, 14.05514005, 20.85411186, 11.0174441 ,  4.56899622])

In [23]:
adv = pd.read_csv('Advertising.csv', usecols=[1,2,3,4])
df = adv.copy()
df.head()

# Bagimli Degisken
y = df['sales']

# Bagimsiz Degiskenler olusturulur (Sales bagimli degisken silinir)
X = df.drop('sales', axis= 1)
# X matrisine 1 ifadesi eklenir ()
X = sm.add_constant(X)

# Kutuphane import edilir
import statsmodels.api as sm
from sklearn.model_selection import train_test_split, cross_val_score, cross_val_predict

# Test - Train ayirma
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.20, random_state=42)

# Model Kurulur
lm = sm.OLS(y_train, X_train)
model = lm.fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  sales   R-squared:                       0.896
Model:                            OLS   Adj. R-squared:                  0.894
Method:                 Least Squares   F-statistic:                     446.6
Date:                Thu, 14 Jul 2022   Prob (F-statistic):           2.53e-76
Time:                        08:28:59   Log-Likelihood:                -306.64
No. Observations:                 160   AIC:                             621.3
Df Residuals:                     156   BIC:                             633.6
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          2.9791      0.354      8.427      0.000       2.281       3.677
TV             0.0447      0.002     28.544      0.000       0.042       0.048
radio          0.1892      0.010     19.518      0.000       0.170       0.208
newspaper      0.0028      0.007      0.392      0.696      -0.011       0.017
==============================================================================
Omnibus:                       67.697   Durbin-Watson:                   2.161
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              240.326
Skew:                          -1.627   Prob(JB):                     6.52e-53
Kurtosis:                       8.046   Cond. No.                         471.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [24]:
df.corr()

TV     radio  newspaper     sales
TV         1.000000  0.054809   0.056648  0.782224
radio      0.054809  1.000000   0.354104  0.576223
newspaper  0.056648  0.354104   1.000000  0.228299
sales      0.782224  0.576223   0.228299  1.000000