# Neden Numpy ? (One #)

## Alt baslik (Double ##) 

## Hucreler bazinda islemler

    b alta satir ekler
    c kopyalar
    x siler 
    v yapistirir

In [1]:
a = [1,2,3,4]
b = [5,6,7,8]
a
b # sadece en son satir calisir

[5, 6, 7, 8]

In [2]:
a

[1, 2, 3, 4]

In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3,4])
b = np.array([5,3,9,10])

In [5]:
a*b

array([ 5,  6, 27, 40])

In [6]:
a-b

array([-4, -1, -6, -6])

In [7]:
b-a

array([4, 1, 6, 6])

In [8]:
a/b

array([0.2       , 0.66666667, 0.33333333, 0.4       ])

In [9]:
a**b

array([      1,       8,   19683, 1048576])

In [10]:
type(a)

numpy.ndarray

In [11]:
np.array([3.14, 4, 2, 13])

array([ 3.14,  4.  ,  2.  , 13.  ])

## np.array([1,2,3], dtype = 'float32')

dtye = 'float32' , dtype = 'int'

In [12]:
np.array([3.14, 4, 2, 13], dtype = 'float32')

array([ 3.14,  4.  ,  2.  , 13.  ], dtype=float32)

In [13]:
np.array([3.14, 4, 2, 13], dtype = int)

array([ 3,  4,  2, 13])

In [14]:
np.array([3.14, 2], dtype = str)

array(['3.14', '2'], dtype='<U4')

In [15]:
# Sifirdan array olusturma

In [16]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
np.ones((3,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [18]:
np.full((3,6), 3, dtype = 'float32')

array([[3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3.]], dtype=float32)

In [19]:
np.full((2,6), 3.4)

array([[3.4, 3.4, 3.4, 3.4, 3.4, 3.4],
       [3.4, 3.4, 3.4, 3.4, 3.4, 3.4]])

In [20]:
np.arange(0,30, 4) # 0 dan 30 kadar 4 er 4 er dogrusal dizi olusur

array([ 0,  4,  8, 12, 16, 20, 24, 28])

In [21]:
np.linspace(0,1, 10) #0 ile 1 arasini 10 esit parcaya bolen dograsl dizi

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [22]:
ln1 = np.linspace(0,1, 10) #0 ile 1 arasini 10 esit parcaya bolen dograsl dizi

In [23]:
type(ln1)

numpy.ndarray

In [24]:
ar01 = np.ones((3,5), dtype = int)

In [25]:
ar01

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [26]:
type(ar01)

numpy.ndarray

In [27]:
# tek boyutlu array = Vektor
# 2 boyutlu array = matris

In [28]:
np.random.normal(10, 4, (3,4)) # ortalamasi 10 standart sapmasi 4 olan 3,4 Matris 

array([[12.97503034,  8.05764032, 11.54311645, 13.8214527 ],
       [ 9.08104663, 14.49583952, 11.90081754, 13.09848794],
       [15.83159661, 11.78986759, 12.26323223,  4.29579152]])

In [48]:
np.random.randint(0,20, (3,3)) #RandomInteger #0-20 arasindan Random 3,3 Matris olustur

array([[11,  5, 15],
       [ 4, 18,  8],
       [19,  9,  1]])

# Ozellikleri

* **ndim** : boyut sayisi
* **shape** : boyut bilgisi
* **size** : toplam eleman sayisi
* **dtype** : array veri tipi

In [32]:
np.random.randint(10, size = 5)

array([8, 9, 8, 7, 3])

In [187]:
np.random.randint(10, size = (2,3,4))

array([[[3, 9, 7, 4],
        [2, 0, 3, 9],
        [7, 7, 4, 3]],

       [[8, 6, 9, 5],
        [5, 4, 7, 3],
        [3, 7, 0, 3]]])

In [33]:
a = np.random.randint(10, size = 5)

In [34]:
a.ndim 

1

In [35]:
a.shape

(5,)

In [36]:
a.size

5

In [37]:
a.dtype

dtype('int64')

In [41]:
b = np.random.randint(10, size = (3,5))
b

array([[2, 0, 6, 2, 4],
       [8, 4, 1, 5, 0],
       [1, 6, 8, 7, 7]])

In [42]:
b.ndim

2

In [43]:
b.shape

(3, 5)

In [44]:
b.size

15

In [45]:
b.dtype

dtype('int64')

In [50]:
np.random.randint(0,20, (3,3))

array([[12,  6,  8],
       [10, 14,  1],
       [ 2, 15,  9]])

## Reshape

In [52]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
np.arange(1,10).size

9

In [53]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
b = np.arange(1,19)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [61]:
b.size

18

In [91]:
b.reshape((6,3)) # 3X3 matris yapar ama kaydetmez atama yapmak gerekir !!!

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [93]:
b # b gordugun iuzere ayni

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [79]:
c = np.arange(10)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
c.ndim

1

In [84]:
e = c.reshape((1,10))
e.ndim

2

# Array Birlestirme (Concatenate)

In [94]:
x = np.array([1,2,3])
y = np.array([5,6,7])

In [99]:
np.concatenate([x,y])

array([1, 2, 3, 5, 6, 7])

In [100]:
z = np.array([7,8,9])

In [101]:
np.concatenate([x,y,z])

array([1, 2, 3, 5, 6, 7, 7, 8, 9])

In [102]:
np.concatenate([x,z,y])

array([1, 2, 3, 7, 8, 9, 5, 6, 7])

In [ ]:
# iki boyutta concatenate (birlestirme)

In [107]:
f = np.array([[1,2,3],
              [4,5,6]])

In [112]:
np.concatenate([f,f]) # axis = 0 default bu yuzden ALT ALTA EKLER (satir bazinda ekleme)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

# **axis = 1**

In [113]:
np.concatenate([f,f], axis = 1) # YAN YANA EKLER (sutun bazinda ekleme)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [114]:
np.concatenate([f,f,f,f])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [115]:
np.concatenate([f,f,f,f], axis = 1 )

array([[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6]])

# Array Ayirma (np.split)

In [117]:
g = np.array([1,2,3,99,98,3,2,1])
g

array([ 1,  2,  3, 99, 98,  3,  2,  1])

In [122]:
np.split(g, [3,5]) # Not iki sayi varsa 3 Parcaya boler dikkat

[array([1, 2, 3]), array([99, 98]), array([3, 2, 1])]

In [120]:
a,b,c = np.split(g, [3,5])
a

array([1, 2, 3])

In [121]:
b

array([99, 98])

In [123]:
c

array([3, 2, 1])

## iki boyutlu ayirma (np.vsplit, np.hsplit)

In [132]:
m = np.arange(16).reshape((4,4))
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [133]:
np.vsplit(m, [2]) # 2. Indexe kadar ayir 0,1 indexleri alir

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [134]:
alt, ust = np.vsplit(m, [2])
ust

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [135]:
alt

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [137]:
np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [141]:
sol, sag = np.hsplit(m, [2])

In [142]:
sol

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [143]:
sag

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# Array Siralama (Sorting)

In [145]:
v = np.array([2,1,4,4,3])

In [147]:
np.sort(v)  # v degismez

array([1, 2, 3, 4, 4])

In [150]:
v

array([2, 1, 4, 4, 3])

In [151]:
v.sort() # V degisti !!!!!!!!

In [152]:
v

array([1, 2, 3, 4, 4])

## iki Boyutlu Siralama

In [176]:
m = np.random.randint(0,30, (3,3))
m

array([[ 7,  5, 14],
       [21, 20,  3],
       [11,  5,  0]])

In [177]:
np.sort(m, axis = 1 ) # Satirlari siralar

array([[ 5,  7, 14],
       [ 3, 20, 21],
       [ 0,  5, 11]])

In [178]:
np.sort(m, axis = 0) # Sutunlari siralar

array([[ 7,  5,  0],
       [11,  5,  3],
       [21, 20, 14]])

# Inde ile Elemanlara Ulasmak

In [194]:
a = np.random.randint(30, size = 10)
a

array([ 8,  6,  1,  3, 23, 13, 11, 21, 26, 23])

In [195]:
a[0]

8

In [196]:
a[-1]

23

In [199]:
a[0] = 100
a

array([100,   6,   1,   3,  23,  13,  11,  21,  26,  23])

In [202]:
m = np.random.randint(100, size = (3,5))
m

array([[80, 84, 54,  7, 15],
       [20, 59, 16, 24, 55],
       [91, 62, 76, 48, 54]])

In [203]:
m[0,1]

84

In [204]:
m[2,0]

91

## Array'a farkli type de veri eklemeye calismak

In [205]:
m[0,0] = 3.14
m[0,0]

3

In [208]:
type(m[0,0]) # Integer ekliyor sadece

numpy.int64

# Slicing ile Elemanlara Ulasmak(Array alt kumesine erismek)

In [210]:
k = np.arange(20,30)
k

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [211]:
k[0:3]

array([20, 21, 22])

In [212]:
k[:3]

array([20, 21, 22])

In [213]:
k[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [214]:
k[1::2]

array([21, 23, 25, 27, 29])

In [215]:
k[::3]

array([20, 23, 26, 29])

In [216]:
## iki Boyutlu slice islemleri

In [218]:
l = np.random.randint(10, size = (5,5))
l

array([[6, 8, 6, 2, 5],
       [2, 5, 3, 3, 8],
       [0, 8, 1, 8, 8],
       [5, 2, 7, 1, 2],
       [6, 3, 3, 7, 0]])

In [219]:
l[:,0] # Tum satirlari al , birinci sutunu sec demek

array([6, 2, 0, 5, 6])

In [224]:
l[:,0:2] # Tum satirlari al , 0 ve 1. sutunu sec demek

array([[6, 8],
       [2, 5],
       [0, 8],
       [5, 2],
       [6, 3]])

In [232]:
l[0,:] # 0. satir Tum Sutunlar

array([6, 8, 6, 2, 5])

In [233]:
l[0]

array([6, 8, 6, 2, 5])

In [234]:
l[1:3,0:2]

array([[2, 5],
       [0, 8]])

In [236]:
l[3,0]

5

# Alt Kume  Uzerinde Islmeler

In [254]:
a = np.random.randint(0,10, size = (5,5))
a

array([[3, 7, 9, 2, 3],
       [2, 7, 5, 4, 4],
       [6, 2, 7, 5, 1],
       [2, 1, 3, 9, 5],
       [6, 4, 3, 1, 0]])

In [255]:
alt_kume_a = a[0:3, 0:2]
alt_kume_a

array([[3, 7],
       [2, 7],
       [6, 2]])

In [256]:
alt_kume_a[0,0] = 999 # A nin alt kumesindeki degisiklik A yi etkiliyor Dikkat !!!
alt_kume_a

array([[999,   7],
       [  2,   7],
       [  6,   2]])

In [257]:
a # A nin alt kumesindeki degisiklik A yi etkiliyor Dikkat !!!

array([[999,   7,   9,   2,   3],
       [  2,   7,   5,   4,   4],
       [  6,   2,   7,   5,   1],
       [  2,   1,   3,   9,   5],
       [  6,   4,   3,   1,   0]])

In [261]:
m = np.random.randint(10, size = (5,5))
m

array([[3, 3, 2, 3, 7],
       [2, 1, 9, 4, 3],
       [4, 8, 2, 5, 5],
       [7, 2, 7, 3, 2],
       [8, 5, 8, 4, 4]])

In [262]:
b = m[0:3, 0:2].copy()
b

array([[3, 3],
       [2, 1],
       [4, 8]])

In [263]:
b[0,0] = 1000
b

array([[1000,    3],
       [   2,    1],
       [   4,    8]])

In [264]:
m # m de degisiklik olmadi 

array([[3, 3, 2, 3, 7],
       [2, 1, 9, 4, 3],
       [4, 8, 2, 5, 5],
       [7, 2, 7, 3, 2],
       [8, 5, 8, 4, 4]])

# Fancy Index ile Elemanlar Erismek 

In [267]:
v = np.arange(0,30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [268]:
v[1]

3

In [269]:
v[3]

9

In [270]:
v[5]

15

In [272]:
[v[1], v[3], v[5]]

[3, 9, 15]

In [273]:
al_getir = [1,3,5]

v[al_getir]

array([ 3,  9, 15])

## iki boyutta Fancy

In [277]:
m = np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [278]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [279]:
m[satir, sutun]

array([1, 5])

## Basit index ile Fancy index

In [280]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [282]:
m[0, [1,2]] # m[satir, sutun] , 0. satirin 1 ve 2. sutunlarini al diyor 

array([1, 2])

In [283]:
m[1, [1,2]] # m[satir, sutun] , 1. satirin 1 ve 2. sutunlarini al diyor 

array([4, 5])

## Slice ile Fancy beraber kullanim

In [295]:
m = np.arange(18).reshape((3,6))
m

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [296]:
m[0:2, [1,2]]  # sifir ve 1. satirlardan, 1 ve 2. stunlari al diyor

array([[1, 2],
       [7, 8]])

In [297]:
m[[0,1],[2,5]] # Enterasan m[0,2] ve m[1,5] aliniyor 

array([ 2, 11])

In [298]:
m[1,5]

11

# Kosullu Elemanlar

In [300]:
v = np.array([1,2,3,4,5])

In [307]:
v > 3

array([False, False, False,  True,  True])

In [302]:
v[v < 3]

array([1, 2])

In [305]:
v[v <= 4]

array([1, 2, 3, 4])

In [306]:
v[v != 3]

array([1, 2, 4, 5])

# Matematiksel Islemler

In [316]:
v =  np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [312]:
print(v - 1 , v**2, )

[0 1 2 3 4] [ 1  4  9 16 25]


In [313]:
#ufunc

In [314]:
np.subtract(v, 1) # v-1 yapar

array([0, 1, 2, 3, 4])

In [315]:
np.add(v, 2)

array([3, 4, 5, 6, 7])

In [317]:
np.multiply(v, 10)

array([10, 20, 30, 40, 50])

In [318]:
np.divide(v, 2)

array([0.5, 1. , 1.5, 2. , 2.5])

In [319]:
np.power(v, 3)

array([  1,   8,  27,  64, 125])

In [320]:
np.mod(v, 2) # v % 2 

array([1, 0, 1, 0, 1])

In [321]:
np.absolute(v) # mutlak deger alir

array([1, 2, 3, 4, 5])

In [324]:
np.absolute(np.array([-99]))

array([99])

In [326]:
np.sin(90)

0.8939966636005579

In [327]:
q = np.array([1,2,3])

In [330]:
np.log(q)

array([0.        , 0.69314718, 1.09861229])

In [331]:
np.log10(10)

1.0

In [372]:
#?np # help(np) ===> cok uzun aciklama veriyor

# Numpy ile iki bilinmeyenli Denklem Cozumu

3x + y = 8

2x + 4y = 22

In [340]:
a = np.array([[3,1],   # katsayilari gir ayri ayri
              [2,4]])
b = np.array([8, 22]) # sonuclari gir

In [342]:
solution = np.linalg.solve(a,b)
solution # x= 1 ,  y = 5

array([1., 5.])

In [361]:
a = np.array([[3,1,2],   # katsayilari gir ayri ayri
              [2,3,7],
             [2,2,3]])
b = np.array([12, 31, 16]) # sonuclari gir

In [362]:
solution = np.linalg.solve(a,b)
solution # x= 1 ,  y = 5

array([1.18181818, 1.90909091, 3.27272727])

## Uc bilinmeyenli cozumu 

In [370]:
e = np.array([[3,-2,4],   # katsayilari gir ayri ayri
              [2,3,2],
             [1,1,1]])
f = np.array([5, 7, 3]) # sonuclari gir

In [371]:
cozum = np.linalg.solve(e,f)
cozum

array([1., 1., 1.])