# Neden Numpy ? (One #)

## Alt baslik (Double ##) 

## Hucreler bazinda islemler

    b alta satir ekler
    c kopyalar
    x siler 
    v yapistirir

In [8]:
a = [1,2,3,4]
b = [5,6,7,8]
a
b # sadece en son satir calisir

[5, 6, 7, 8]

In [7]:
a

[1, 2, 3, 4]

In [10]:
import numpy as np

In [20]:
a = np.array([1,2,3,4])
b = np.array([5,3,9,10])

In [21]:
a*b

array([ 5,  6, 27, 40])

In [22]:
a-b

array([-4, -1, -6, -6])

In [23]:
b-a

array([4, 1, 6, 6])

In [24]:
a/b

array([0.2       , 0.66666667, 0.33333333, 0.4       ])

In [25]:
a**b

array([      1,       8,   19683, 1048576])

In [26]:
type(a)

numpy.ndarray

In [28]:
np.array([3.14, 4, 2, 13])

array([ 3.14,  4.  ,  2.  , 13.  ])

## np.array([1,2,3], dtype = 'float32')

dtye = 'float32' , dtype = 'int'

In [30]:
np.array([3.14, 4, 2, 13], dtype = 'float32')

array([ 3.14,  4.  ,  2.  , 13.  ], dtype=float32)

In [32]:
np.array([3.14, 4, 2, 13], dtype = int)

array([ 3,  4,  2, 13])

In [65]:
np.array([3.14, 2], dtype = str)

array(['3.14', '2'], dtype='<U4')

In [33]:
# Sifirdan array olusturma

In [35]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [36]:
np.ones((3,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [38]:
np.full((3,6), 3, dtype = 'float32')

array([[3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3.]], dtype=float32)

In [47]:
np.full((2,6), 3.4)

array([[3.4, 3.4, 3.4, 3.4, 3.4, 3.4],
       [3.4, 3.4, 3.4, 3.4, 3.4, 3.4]])

In [50]:
np.arange(0,30, 4) # 0 dan 30 kadar 4 er 4 er dogrusal dizi olusur

array([ 0,  4,  8, 12, 16, 20, 24, 28])

In [51]:
np.linspace(0,1, 10) #0 ile 1 arasini 10 esit parcaya bolen dograsl dizi

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [52]:
ln1 = np.linspace(0,1, 10) #0 ile 1 arasini 10 esit parcaya bolen dograsl dizi

In [53]:
type(ln1)

numpy.ndarray

In [55]:
ar01 = np.ones((3,5), dtype = int)

In [56]:
ar01

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [57]:
type(ar01)

numpy.ndarray

In [58]:
# tek boyutlu array = Vektor
# 2 boyutlu array = matris

In [59]:
np.random.normal(10, 4, (3,4)) # ortalamasi 10 standart sapmasi 4 olan 3,4 Matris 

array([[11.27721022,  9.72255407,  7.82698843,  6.6349811 ],
       [11.66131088, 12.66209187,  6.4169959 , 10.59090116],
       [ 8.52984072,  8.01139976, 14.7891896 ,  8.43135898]])

In [61]:
np.random.randint(0,20, (3,3)) #RandomInteger #0-20 arasindan Random 3,3 Matris olustur

array([[ 4, 15, 13],
       [14,  2, 18],
       [ 1,  3,  2]])