# Pandas Serisi Olusturmak

In [2]:
import pandas as pd
import numpy as np

In [3]:
pd.Series([99,112,70,-3,11])  # Degerleri index ile beraber tutar internal 

0     99
1    112
2     70
3     -3
4     11
dtype: int64

In [4]:
seri = pd.Series([99,112,70,-3,11])
type(seri)

pandas.core.series.Series

In [6]:
seri.axes # index bilgisine ulas, index 5'e kadar 5 dahil degil

[RangeIndex(start=0, stop=5, step=1)]

In [7]:
seri.dtype

dtype('int64')

In [9]:
seri.ndim # Boyut

1

In [10]:
seri.values # index olmadan sadece veriler ulasmak

array([ 99, 112,  70,  -3,  11])

In [12]:
seri.head()

0     99
1    112
2     70
3     -3
4     11
dtype: int64

In [14]:
seri.tail(3)

2    70
3    -3
4    11
dtype: int64

## index isimlendirmesi

In [18]:
seri = pd.Series([99,112,70,-3,11])
seri

0     99
1    112
2     70
3     -3
4     11
dtype: int64

seri = pd.Series([99,112,70,-3,11], index = [1,3,5,7,9])
seri

In [24]:
seri = pd.Series([99,112,70,-3,11], index = ['a', 3, 'c', 7,9])
seri

a     99
3    112
c     70
7     -3
9     11
dtype: int64

In [25]:
seri['a']

99

In [27]:
seri['a':'c']

a     99
3    112
c     70
dtype: int64

## Sozluk uzerinde Liste Olusturmak

In [28]:
sozluk = {'reg':10, 'log':11, 'cart':12}

In [29]:
seri = pd.Series(sozluk)
seri

reg     10
log     11
cart    12
dtype: int64

In [31]:
seri['log':]

log     11
cart    12
dtype: int64

## Iki seriyi birlestirmek (concat)

In [39]:
seri

reg     10
log     11
cart    12
dtype: int64

In [42]:
seri2 = pd.Series({'reg':1999, 'log':77, 'cart':555})
seri2

reg     1999
log       77
cart     555
dtype: int64

In [43]:
pd.concat([seri, seri2])

reg       10
log       11
cart      12
reg     1999
log       77
cart     555
dtype: int64

In [44]:
pd.concat([seri, seri2], axis = 1)

0     1
reg   10  1999
log   11    77
cart  12   555

In [45]:
#?pd.concat ====> Concatenate

# Eleman Birlestirme

In [49]:
a = np.array([1,2,33,444,75])
seri = pd.Series(a)
seri         

0      1
1      2
2     33
3    444
4     75
dtype: int64

In [51]:
seri[0]

1

In [52]:
seri[0:3]

0     1
1     2
2    33
dtype: int64

In [54]:
seri = pd.Series([1221, 200, 150, 99],
               index = ['reg', 'log', 'cart', 'rf'])

In [56]:
seri

reg     1221
log      200
cart     150
rf        99
dtype: int64

In [58]:
seri.index

Index(['reg', 'log', 'cart', 'rf'], dtype='object')

In [59]:
seri.axes

[Index(['reg', 'log', 'cart', 'rf'], dtype='object')]

In [60]:
seri.keys

<bound method Series.keys of reg     1221
log      200
cart     150
rf        99
dtype: int64>

In [61]:
list(seri.items())

[('reg', 1221), ('log', 200), ('cart', 150), ('rf', 99)]

In [66]:
seri2 = pd.Series([999, 222, 777, 888],
               index = ['reg', 'log', 'cart', 'rf'])

In [67]:
s1 = pd.concat([seri, seri2], axis = 1)
s1

0    1
reg   1221  999
log    200  222
cart   150  777
rf      99  888

In [68]:
list(s1.items())

[(0,
  reg     1221
  log      200
  cart     150
  rf        99
  Name: 0, dtype: int64),
 (1,
  reg     999
  log     222
  cart    777
  rf      888
  Name: 1, dtype: int64)]

In [69]:
s1[0]

reg     1221
log      200
cart     150
rf        99
Name: 0, dtype: int64

In [73]:
s1[0][0] # s1[0,0] ====> hata verir !!!!!

1221

## Eleman Sorgulama

In [78]:
'reg' in seri

True

In [79]:
'a' in seri

False

In [80]:
seri['reg']

1221

In [81]:
seri[['reg', 'rf']]

reg    1221
rf       99
dtype: int64

In [82]:
## Eleman degistirme

In [83]:
seri['reg']

1221

In [85]:
seri['reg'] = 'Abdullah'
seri['reg']

'Abdullah'

# Pandas DataFrame Olusturma

In [86]:
l = [1,2,39,67,90]
l

[1, 2, 39, 67, 90]

In [89]:
pd.DataFrame(l, columns = ['degisken_ismi'])

degisken_ismi
0              1
1              2
2             39
3             67
4             90

In [90]:
m = np.arange(1,10).reshape(3,3)
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [92]:
pd.DataFrame(m, columns = ['var1', 'var2', 'var3'])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

## df Isimlendirme

In [93]:
df = pd.DataFrame(m, columns = ['var1', 'var2', 'var3'])
df.head()

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [94]:
df.columns

Index(['var1', 'var2', 'var3'], dtype='object')

## Kolon Adi Degistirme

In [95]:
df.columns = ('deg1', 'deg2', 'deg3')
df

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [96]:
type(df)

pandas.core.frame.DataFrame

In [97]:
df.axes  # Satir ve Sutun bilgisine ulasilir

[RangeIndex(start=0, stop=3, step=1),
 Index(['deg1', 'deg2', 'deg3'], dtype='object')]

In [98]:
df.ndim

2

In [99]:
df.shape

(3, 3)

In [100]:
df.size # eleman sayisi

9

In [101]:
df.values #!!!!! Numpy arraya cevirip degerleri verdi

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [116]:
a = np.array([1,2,3,4,5])
b = pd.DataFrame(a, columns = ['deg1'])
b

deg1
0     1
1     2
2     3
3     4
4     5

In [119]:
b['deg1'][0]

1

# Eleman Islemleri

In [129]:
s1 = np.random.randint(10, size = 5)
s2 = np.random.randint(10, size = 5)
s3 = np.random.randint(10, size = 5)

In [133]:
sozluk = {'var1':s1, 'var2':s2, 'var3':3}
sozluk

{'var1': array([6, 8, 0, 1, 2]), 'var2': array([5, 7, 3, 4, 7]), 'var3': 3}

In [138]:
df = pd.DataFrame(sozluk)
df

var1  var2  var3
0     6     5     3
1     8     7     3
2     0     3     3
3     1     4     3
4     2     7     3

In [167]:
df[0:1]

var1  var2  var3
0     6     5     3

# Index Degistirmek

In [168]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [169]:
df.index = ['a', 'b', 'c', 'd', 'e']
df

var1  var2  var3
a     6     5     3
b     8     7     3
c     0     3     3
d     1     4     3
e     2     7     3

In [171]:
df['c':'e']

var1  var2  var3
c     0     3     3
d     1     4     3
e     2     7     3

## Silme Islemi

df.drop(0, axis = 0 , inplace = True)

In [173]:
df.drop('a', axis = 0) # Dikkat kalici silmez !!!!!

var1  var2  var3
b     8     7     3
c     0     3     3
d     1     4     3
e     2     7     3

In [174]:
df # ana DataFrame ayni duruyor

var1  var2  var3
a     6     5     3
b     8     7     3
c     0     3     3
d     1     4     3
e     2     7     3

In [175]:
df.drop('a', axis = 0, inplace = True) 
df

var1  var2  var3
b     8     7     3
c     0     3     3
d     1     4     3
e     2     7     3

In [176]:
# Fancy ile Silme

In [177]:
l = ['c', 'd']
df.drop(l, axis = 0)

var1  var2  var3
b     8     7     3
e     2     7     3

## in (DataFrame icinde mi ? Sorgulama)

In [178]:
'var1' in df

True

In [181]:
l = ['var1', 'xxx', 'var3']

In [182]:
for i in l:
    print(i in df)

True
False
True


## Yeni Sutun Eklemek ve Silmek (New Column added and deleted)

In [183]:
df

var1  var2  var3
b     8     7     3
c     0     3     3
d     1     4     3
e     2     7     3

In [185]:
df['var4'] = df['var1'] * df['var2']
df

var1  var2  var3  var4
b     8     7     3    56
c     0     3     3     0
d     1     4     3     4
e     2     7     3    14

In [186]:
df.drop('var4', axis = 1)

var1  var2  var3
b     8     7     3
c     0     3     3
d     1     4     3
e     2     7     3

In [188]:
df.drop('var4', axis = 1, inplace = True)
df

var1  var2  var3
b     8     7     3
c     0     3     3
d     1     4     3
e     2     7     3

In [189]:
l = ['var1', 'var2']
df.drop(l, axis = 1)

var3
b     3
c     3
d     3
e     3

# Gozlem ve Degisken Secimi : loc & iloc

In [192]:
m = np.random.randint(1,30, size = (10,3))
df = pd.DataFrame(m, columns = ['v1', 'v2', 'v3'])
df                

v1  v2  v3
0  17  11  23
1  26  16  29
2  26  15  27
3   8  18   6
4  29   2  23
5  20  27   2
6  16   2   9
7  12  27   4
8  17   5  24
9  29  19  11

## loc : Tanimlandigi sekli ile secim yapar.

In [201]:
df.loc[0:3] # 3. Indeksi de alirrrrr

v1  v2  v3
0  17  11  23
1  26  16  29
2  26  15  27
3   8  18   6

## iloc : alisik oldugumuz indeksleme mantigi ile secim yapar.

In [203]:
df.iloc[0:3]  # 3. indeks dahil degildir.

v1  v2  v3
0  17  11  23
1  26  16  29
2  26  15  27

In [204]:
df.iloc[0,0]

17

In [206]:
# df.loc[0,0]   ======> Hata verir

In [207]:
df.iloc[:3,:2]

v1  v2
0  17  11
1  26  16
2  26  15

In [210]:
# df.loc[:3,:2]    ======> Hata verir

In [211]:
df.loc[0:3, 'v3']

0    23
1    29
2    27
3     6
Name: v3, dtype: int64

In [213]:
#df.iloc[0:3, 'v3'] =======> Hata verir

In [216]:
df.iloc[0:3]['v3']

0    23
1    29
2    27
Name: v3, dtype: int64

# Kosullu Eleman Islmeleri

In [218]:
df

v1  v2  v3
0  17  11  23
1  26  16  29
2  26  15  27
3   8  18   6
4  29   2  23
5  20  27   2
6  16   2   9
7  12  27   4
8  17   5  24
9  29  19  11

In [219]:
df['v1']

0    17
1    26
2    26
3     8
4    29
5    20
6    16
7    12
8    17
9    29
Name: v1, dtype: int64

In [223]:
df['v1'][0:3]

0    17
1    26
2    26
Name: v1, dtype: int64

In [224]:
df[0:3]

v1  v2  v3
0  17  11  23
1  26  16  29
2  26  15  27

In [225]:
df[0:3]['v1']

0    17
1    26
2    26
Name: v1, dtype: int64

In [226]:
df[0:3][['v1', 'v2']] # Fancy islemi yapilir , degilse hata verir

v1  v2
0  17  11
1  26  16
2  26  15

In [227]:
df.v1

0    17
1    26
2    26
3     8
4    29
5    20
6    16
7    12
8    17
9    29
Name: v1, dtype: int64

In [230]:
df[df.v1 > 20] # =====> Bu DataFrame in tamamidir, kosulu saglayanlardir

v1  v2  v3
1  26  16  29
2  26  15  27
4  29   2  23
9  29  19  11

In [232]:
df[df.v1 > 20]['v1']  # Bu DataFrame in kosulu saglayanlarin v1 stunudur sadece

1    26
2    26
4    29
9    29
Name: v1, dtype: int64

In [233]:
df[(df.v1 > 20) & (df.v3 < 25)]

v1  v2  v3
4  29   2  23
9  29  19  11

In [236]:
df[(df.v1 > 20) & (df.v3 < 25)][['v2', 'v3']]

v2  v3
4   2  23
9  19  11