In [97]:
import numpy as np
import pandas as pd
import seaborn as sns

import warnings
warnings.simplefilter(action='ignore')  # 'default'

df = pd.DataFrame({'c1': list('abcdefg')})
df.loc[5, 'c1'] = 'Value'
df

c1
0      a
1      b
2      c
3      d
4      e
5  Value
6      g

In [2]:
df = df.assign(c2 = df.c1)
df

c1     c2
0      a      a
1      b      b
2      c      c
3      d      d
4      e      e
5  Value  Value
6      g      g

In [21]:
df.loc[df['c1'] == 'Value', 'c2'] = 10
df

c1  c2
0      a   a
1      b   b
2      c   c
3      d   d
4      e   e
5  Value  10
6      g   g

In [22]:
df[5:6].values

array([['Value', 10]], dtype=object)

In [29]:
df5 = df[['c1','c2']][5:6]
df5

c1  c2
5  Value  10

In [36]:
df.iloc[0] = df5
df

c1  c2
0  Value  10
1      b   b
2      c   c
3      d   d
4      e   e
5  Value  10
6      g   g

In [38]:
list1  = [0,3,6]
df.iloc[list1] =df5
df

c1  c2
0  Value  10
1      b   b
2      c   c
3  Value  10
4      e   e
5  Value  10
6  Value  10

In [98]:
df = sns.load_dataset('diamonds')
df = df.select_dtypes(include = ['float64', 'int64'])
df = df.dropna()
df.head()

carat  depth  table  price     x     y     z
0   0.23   61.5   55.0    326  3.95  3.98  2.43
1   0.21   59.8   61.0    326  3.89  3.84  2.31
2   0.23   56.9   65.0    327  4.05  4.07  2.31
3   0.29   62.4   58.0    334  4.20  4.23  2.63
4   0.31   63.3   58.0    335  4.34  4.35  2.75

In [49]:
#df[:1] = df[1:2]
#df.head()

In [50]:
# Yeni Kutuphane import ettik

from sklearn.neighbors import LocalOutlierFactor

In [51]:
# n_neighbors = komsu sayisi
# contamination = yogunluk ifade 
# 20 ve 0.1 degeri Veri sayisi ve is bilgisine dayali olarak belirlendi varsadik

clf = LocalOutlierFactor(n_neighbors= 20, contamination= 0.1)

In [52]:
# clf nesnesi LocalOutlierFactorun bicimsel ozelliklerini kullaniyor

clf

LocalOutlierFactor(contamination=0.1)

In [53]:
# Algoritmayi calistirma islemi 

clf.fit_predict(df)

array([-1, -1, -1, ...,  1,  1,  1])

In [54]:
# Her bir gozlem birimi icin olusturulmus scorelar var

df_score = clf.negative_outlier_factor_

In [55]:
df_score[0:10]

array([-1.58352526, -1.59732899, -1.62278873, -1.33002541, -1.30712521,
       -1.28408436, -1.28428162, -1.26458706, -1.28422952, -1.27351342])

In [56]:
# Degerler arasindaki farklari inceliyoruz

np.sort(df_score)[0:10]

array([-8.60430658, -8.20889984, -5.86084355, -4.98415175, -4.81502092,
       -4.81502092, -4.61522833, -4.37081214, -4.29842288, -4.10492387])

In [57]:
# 13. Degeri esik degeri olsun dedik

esik_deger = np.sort(df_score)[13]
esik_deger

-3.823787967755565

In [58]:
aykiri_olmayan_tf = df_score > esik_deger
aykiri_olmayan_tf

array([ True,  True,  True, ...,  True,  True,  True])

In [59]:
# Aykiri Olmayan degerler ulasmak

df[aykiri_olmayan_tf]

carat  depth  table  price     x     y     z
0       0.23   61.5   55.0    326  3.95  3.98  2.43
1       0.21   59.8   61.0    326  3.89  3.84  2.31
2       0.23   56.9   65.0    327  4.05  4.07  2.31
3       0.29   62.4   58.0    334  4.20  4.23  2.63
4       0.31   63.3   58.0    335  4.34  4.35  2.75
...      ...    ...    ...    ...   ...   ...   ...
53935   0.72   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75   62.2   55.0   2757  5.83  5.87  3.64

[53926 rows x 7 columns]

In [60]:
df[~aykiri_olmayan_tf]

carat  depth  table  price     x      y      z
6341    1.00   44.0   53.0   4032  6.31   6.24   4.12
10377   1.09   43.0   54.0   4778  6.53   6.55   4.12
24067   2.00   58.9   57.0  12210  8.09  58.90   8.06
31230   0.45   68.6   57.0    756  4.73   4.50   3.19
35633   0.29   62.8   44.0    474  4.20   4.24   2.65
36503   0.30   51.0   67.0    945  4.67   4.62   2.37
38840   0.73   70.8   55.0   1049  5.51   5.34   3.84
41918   1.03   78.2   54.0   1262  5.72   5.59   4.42
45688   0.70   71.6   55.0   1696  5.47   5.28   3.85
48410   0.51   61.8   54.7   1970  5.12   5.15  31.80
49189   0.51   61.8   55.0   2075  5.15  31.80   5.12
50773   0.81   68.8   79.0   2301  5.26   5.20   3.58
52860   0.50   79.0   73.0   2579  5.21   5.18   4.09
52861   0.50   79.0   73.0   2579  5.21   5.18   4.09

In [63]:
baski_degeri = df[df_score == esik_deger]
baski_degeri

carat  depth  table  price     x    y     z
31230   0.45   68.6   57.0    756  4.73  4.5  3.19

In [68]:
df[~aykiri_olmayan_tf]

carat  depth  table  price     x      y      z
6341    1.00   44.0   53.0   4032  6.31   6.24   4.12
10377   1.09   43.0   54.0   4778  6.53   6.55   4.12
24067   2.00   58.9   57.0  12210  8.09  58.90   8.06
31230   0.45   68.6   57.0    756  4.73   4.50   3.19
35633   0.29   62.8   44.0    474  4.20   4.24   2.65
36503   0.30   51.0   67.0    945  4.67   4.62   2.37
38840   0.73   70.8   55.0   1049  5.51   5.34   3.84
41918   1.03   78.2   54.0   1262  5.72   5.59   4.42
45688   0.70   71.6   55.0   1696  5.47   5.28   3.85
48410   0.51   61.8   54.7   1970  5.12   5.15  31.80
49189   0.51   61.8   55.0   2075  5.15  31.80   5.12
50773   0.81   68.8   79.0   2301  5.26   5.20   3.58
52860   0.50   79.0   73.0   2579  5.21   5.18   4.09
52861   0.50   79.0   73.0   2579  5.21   5.18   4.09

In [91]:
df_outlier = df[~aykiri_olmayan_tf]
df_outlier

carat  depth  table  price     x      y      z
6341    1.00   44.0   53.0   4032  6.31   6.24   4.12
10377   1.09   43.0   54.0   4778  6.53   6.55   4.12
24067   2.00   58.9   57.0  12210  8.09  58.90   8.06
31230   0.45   68.6   57.0    756  4.73   4.50   3.19
35633   0.29   62.8   44.0    474  4.20   4.24   2.65
36503   0.30   51.0   67.0    945  4.67   4.62   2.37
38840   0.73   70.8   55.0   1049  5.51   5.34   3.84
41918   1.03   78.2   54.0   1262  5.72   5.59   4.42
45688   0.70   71.6   55.0   1696  5.47   5.28   3.85
48410   0.51   61.8   54.7   1970  5.12   5.15  31.80
49189   0.51   61.8   55.0   2075  5.15  31.80   5.12
50773   0.81   68.8   79.0   2301  5.26   5.20   3.58
52860   0.50   79.0   73.0   2579  5.21   5.18   4.09
52861   0.50   79.0   73.0   2579  5.21   5.18   4.09

In [99]:
df_outlier[0:] = baski_degeri
df_outlier

carat  depth  table  price     x    y     z
6341    0.45   68.6   57.0  756.0  4.73  4.5  3.19
10377   0.45   68.6   57.0  756.0  4.73  4.5  3.19
24067   0.45   68.6   57.0  756.0  4.73  4.5  3.19
31230   0.45   68.6   57.0  756.0  4.73  4.5  3.19
35633   0.45   68.6   57.0  756.0  4.73  4.5  3.19
36503   0.45   68.6   57.0  756.0  4.73  4.5  3.19
38840   0.45   68.6   57.0  756.0  4.73  4.5  3.19
41918   0.45   68.6   57.0  756.0  4.73  4.5  3.19
45688   0.45   68.6   57.0  756.0  4.73  4.5  3.19
48410   0.45   68.6   57.0  756.0  4.73  4.5  3.19
49189   0.45   68.6   57.0  756.0  4.73  4.5  3.19
50773   0.45   68.6   57.0  756.0  4.73  4.5  3.19
52860   0.45   68.6   57.0  756.0  4.73  4.5  3.19
52861   0.45   68.6   57.0  756.0  4.73  4.5  3.19

In [94]:
df[~aykiri_olmayan_tf]

carat  depth  table  price     x      y      z
6341    1.00   44.0   53.0   4032  6.31   6.24   4.12
10377   1.09   43.0   54.0   4778  6.53   6.55   4.12
24067   2.00   58.9   57.0  12210  8.09  58.90   8.06
31230   0.45   68.6   57.0    756  4.73   4.50   3.19
35633   0.29   62.8   44.0    474  4.20   4.24   2.65
36503   0.30   51.0   67.0    945  4.67   4.62   2.37
38840   0.73   70.8   55.0   1049  5.51   5.34   3.84
41918   1.03   78.2   54.0   1262  5.72   5.59   4.42
45688   0.70   71.6   55.0   1696  5.47   5.28   3.85
48410   0.51   61.8   54.7   1970  5.12   5.15  31.80
49189   0.51   61.8   55.0   2075  5.15  31.80   5.12
50773   0.81   68.8   79.0   2301  5.26   5.20   3.58
52860   0.50   79.0   73.0   2579  5.21   5.18   4.09
52861   0.50   79.0   73.0   2579  5.21   5.18   4.09

In [106]:
df[~aykiri_olmayan_tf] = df_outlier
df[~aykiri_olmayan_tf]

carat  depth  table  price     x    y     z
6341    0.45   68.6   57.0  756.0  4.73  4.5  3.19
10377   0.45   68.6   57.0  756.0  4.73  4.5  3.19
24067   0.45   68.6   57.0  756.0  4.73  4.5  3.19
31230   0.45   68.6   57.0  756.0  4.73  4.5  3.19
35633   0.45   68.6   57.0  756.0  4.73  4.5  3.19
36503   0.45   68.6   57.0  756.0  4.73  4.5  3.19
38840   0.45   68.6   57.0  756.0  4.73  4.5  3.19
41918   0.45   68.6   57.0  756.0  4.73  4.5  3.19
45688   0.45   68.6   57.0  756.0  4.73  4.5  3.19
48410   0.45   68.6   57.0  756.0  4.73  4.5  3.19
49189   0.45   68.6   57.0  756.0  4.73  4.5  3.19
50773   0.45   68.6   57.0  756.0  4.73  4.5  3.19
52860   0.45   68.6   57.0  756.0  4.73  4.5  3.19
52861   0.45   68.6   57.0  756.0  4.73  4.5  3.19